# <a id='toc6_'></a>[DGIdb ambiguous claims](#toc0_)

In [ ]:
merged_alias_primary_collisions_df = pd.read_csv(
    "merged_alias_gene_intersections.csv", na_values=["", "NULL"], keep_default_na=False
)
merged_alias_primary_collisions_df

     gene_symbol      alias_symbol intersect_point source
0          SOAT2             ACAT2           ACAT2   HGNC
1         ACTBP8            ACTBP2          ACTBP2   HGNC
2          APPL1              APPL            APPL   HGNC
3         AKR1B1                AR              AR   HGNC
4        B3GNTL1            B3GNT8          B3GNT8   HGNC
...          ...               ...             ...    ...
2021       USP21      USP23, USP16           USP16   ENSG
2022       USP25             USP21           USP21   ENSG
2023     VDAC1P5     VDAC5P, VDAC3           VDAC3   ENSG
2024      XBP1P1       XBPP1, XBP1            XBP1   ENSG
2025    ZNF322P1   ZNF322B, ZNF322          ZNF322   ENSG

[2026 rows x 4 columns]

In [ ]:
ag_collision_set = set(merged_alias_primary_collisions_df["intersect_point"])

In [ ]:
dgidb_gene_df = pd.read_csv(
    "dgidb_genes_JUNE.tsv", sep="\t", na_values=["", "NULL"], keep_default_na=False
)
dgidb_gene_df

,gene_claim_name,nomenclature,concept_id,gene_name,source_db_name,source_db_version
0,NGFIBA,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14
1,NGFIBB,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14
2,DAX,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14
3,REV-ERBA,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14
4,COUP2,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14
...,...,...,...,...,...,...
80229,KIT,Gene Symbol,hgnc:6342,KIT,Oncomine,v3
80230,HES1,Gene Name,hgnc:5192,HES1,NCI,14-Sep-17
80231,IRF1,Gene Symbol,hgnc:6116,IRF1,Tempus,11-Nov-18
80232,SHFM1,Gene Name,hgnc:10845,SEM1,DTC,9/2/20
80233,NEUROD1,Gene Name,hgnc:7762,NEUROD1,NCI,14-Sep-17

In [ ]:
dgidb_gene_df.loc[dgidb_gene_df["gene_claim_name"] == "HES1"]

,gene_claim_name,nomenclature,concept_id,gene_name,source_db_name,source_db_version
30772,HES1,Gene Symbol,hgnc:5192,HES1,Pharos,10-Apr-24
76844,HES1,Gene Symbol,hgnc:5192,HES1,HGNC,20240408
76845,HES1,Gene Symbol,hgnc:5192,HES1,NCBI,20240410
76846,HES1,Gene Symbol,hgnc:5192,HES1,Ensembl,111
80230,HES1,Gene Name,hgnc:5192,HES1,NCI,14-Sep-17

In [ ]:
dgidb_gene_df.query("gene_name != gene_claim_name")

,gene_claim_name,nomenclature,concept_id,gene_name,source_db_name,source_db_version
0,NGFIBA,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14
1,NGFIBB,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14
2,DAX,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14
3,REV-ERBA,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14
4,COUP2,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14
...,...,...,...,...,...,...
79999,SEPT5,Gene Symbol,hgnc:9164,SEPTIN5,FoundationOneGenes,9/3/20
80014,ENSEMBL:ENSG00000185821,Ensembl Gene ID,hgnc:31305,OR6C76,RussLampel,26-Jul-11
80053,SEPT5,Gene Symbol,hgnc:9164,SEPTIN5,CarisMolecularIntelligence,9/4/20
80166,SEPT6,Gene Symbol,hgnc:15848,SEPTIN6,CarisMolecularIntelligence,9/4/20
80232,SHFM1,Gene Name,hgnc:10845,SEM1,DTC,9/2/20

claims without a symbol/name/identifier
 (there shouldn't be any hooray)

In [ ]:
no_claim_symbols_df = dgidb_gene_df[dgidb_gene_df["gene_claim_name"].isnull()]
no_claim_symbols_df

Empty DataFrame
Columns: [gene_claim_name, nomenclature, concept_id, gene_name, source_db_name, source_db_version]
Index: []

un normalized

In [ ]:
no_name_symbols_df = dgidb_gene_df[dgidb_gene_df["gene_name"].isnull()]
no_name_symbols_df

,gene_claim_name,nomenclature,concept_id,gene_name,source_db_name,source_db_version
0,NGFIBA,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14
1,NGFIBB,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14
2,DAX,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14
3,REV-ERBA,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14
4,COUP2,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14
...,...,...,...,...,...,...
29008,URS00006E35E8_9606,Gene Symbol,NaN,NaN,GO,10-Apr-24
29009,URS0000EA3BA1_9606,Gene Symbol,NaN,NaN,GO,10-Apr-24
29198,TRYPTASE_B2_HUMAN,Gene Symbol,NaN,NaN,GO,10-Apr-24
29199,TRYPTASE_B1_HUMAN,Gene Symbol,NaN,NaN,GO,10-Apr-24
29389,HERVK_113,Gene Symbol,NaN,NaN,Pharos,10-Apr-24

In [ ]:
dgidb_name_set = set(dgidb_gene_df["gene_name"])
len(dgidb_name_set)

12001

In [ ]:
dgidb_gene_claim_name_set = set(dgidb_gene_df["gene_claim_name"])
len(dgidb_gene_claim_name_set)

26739

In [ ]:
hgnc_ensg_gene_symbol_set = hgnc_gene_symbol_set.union(ensg_gene_symbol_set)

In [ ]:
hgnc_ensg_ncbi_gene_symbol_set = hgnc_ensg_gene_symbol_set.union(ncbi_gene_symbol_set)

In [ ]:
hgnc_ensg_alias_symbol_set = hgnc_alias_symbol_set.union(ensg_alias_symbol_set)

In [ ]:
hgnc_ensg_ncbi_alias_symbol_set = hgnc_ensg_alias_symbol_set.union(
    ncbi_alias_symbol_set
)

In [ ]:
print(len(aa_collision_set.intersection(ag_collision_set)))

161

In [ ]:
ambiguous_symbol_set = aa_collision_set.union(ag_collision_set)
print(len(ambiguous_symbol_set))

5865

In [ ]:
ambiguous_symbol_set = set(item.strip() for item in ambiguous_symbol_set)

print(len(ambiguous_symbol_set))

5050

In [ ]:
ambiguous_symbol_set

{'KAR',
 'CLE',
 'TPH2',
 'GGF2',
 'TBP1',
 'BEDP',
 'GS1',
 'ST3GALII',
 'RAM',
 'RPS18',
 'PRL3',
 'LSS, ZRS',
 'RIP2',
 'SAST',
 'OPLL',
 'OFD1P1',
 'HCA1',
 'NY-ESO-1',
 'TCRGV',
 'CLECSF13',
 'L6',
 'PN',
 'TRK-TTT3-5',
 'DOC-1',
 'AOH1',
 'HC2',
 'TRNAMI2',
 'TRFP',
 'TC2',
 'CATMANS',
 'OR11H12',
 'DPK',
 'HN1',
 'IGLV',
 'CMG1',
 'FGF2',
 'RP58',
 'NRXN4',
 'PAK3',
 'WBS',
 'PLAC8',
 'HZF2',
 'HLA-DQB1',
 'ERV1',
 'KAP2.3',
 'JDP1',
 'MPP1',
 'BMI1',
 'ZAC1',
 'RHBDL4',
 'MMP25',
 'XBP1',
 'SSB2',
 'CHP1',
 'KRTAP18.1',
 'II',
 'MBD2',
 'S100A14',
 'H4C12',
 'LACS2',
 'CAIN',
 'MIP-1-beta',
 'p57',
 'CKB1',
 'GCB',
 'SGT1',
 'TIP39',
 'GNT1',
 'CYPIIIA7',
 'CAPH2',
 'H2AC11, H2AC13, H2AC15, H2AC16',
 'AIB1',
 'NG2-6',
 'CKS1',
 'IGEL',
 'PKR1',
 'DRP1',
 'PTB',
 'CD',
 'JUNB',
 'RECQL2',
 'MLN',
 'EVA',
 'p21',
 'CDH1',
 'SCAR1',
 'NIRF',
 'TEM',
 'GAPDH',
 'KRTAP5-1',
 'ANKRD21',
 'TRX-CAT1-8',
 'ASPS',
 'KRTAP2-1',
 'LIN-10',
 'TRA-TGC3-2',
 'VPP3',
 'PCAP',
 'PSCTK2',
 'KRTAP2-4',
 'P55',
 'HIST1H2BI',
 'RAB1',
 'CIR',
 'TRIM49D2P',
 'ORC1',
 'FBLP1',
 'PRR20A, PRR20B, PRR20C, PRR20D',
 'CDR3, TRB',
 'HST',
 'ABP',
 'MAFA',
 'SGS',
 'MSS1',
 'MPP6',
 'LGL1',
 'NG23',
 'PGDS',
 'LIG1',
 'FBS',
 'MR1, PDC',
 'MED1',
 'NTT',
 'SPRING',
 'P63',
 'EMC19',
 'TRG-GCC2-3',
 'RRF',
 'BTN1',
 'B3GN-T1',
 'DCR2',
 'CT90',
 'SPANX-A',
 'AMAC1',
 'OF',
 'P76',
 'BTF2',
 'LGL2',
 'EEF1AKMT4',
 'L7',
 'EPPK1',
 'SXI1',
 'SCA2',
 'ALPI',
 'TEB1',
 'HEPN1',
 'NANOGP3',
 'CYPL1',
 'ANKRD33',
 'GCP',
 'SST3',
 'TNNI3K',
 'SPINT3',
 'FB',
 'GUCA1A',
 'EPM2A',
 'YRRM2',
 'NPIPB5',
 'H2BFK',
 'SGK2',
 'MAGE1',
 'TTF-1',
 'HARS2',
 'HNRNP-G',
 'MGC15397',
 'HSD17',
 'TAF4B',
 'EIF3A',
 'CAP3',
 'MIF',
 'ARC34',
 'THM',
 'NMTC1',
 'KOX5',
 'HLAL',
 'TAP2',
 'GLUD2',
 'ASB-3',
 'ELK3',
 'IQCH',
 'DDC8',
 'SK1',
 'MIP1',
 'MRE11B',
 'S2',
 'ZNF230',
 'XCE',
 'TSG',
 'LAP1',
 'RMD1',
 'IBP',
 'ZRC1',
 'FGQTL2',
 'MSE',
 'TRT-AGT4-1',
 'OR11-11a',
 'ED3',
 'P31',
 'CAF1',
 'IFN-ALPHAI',
 'SHP1',
 'NRP2',
 'Vma2',
 'SPANXE',
 'ARIA',
 'p54',
 'BRF-1',
 'MCM2',
 'KLK6',
 'IGHEP1',
 'OCC1',
 'PP2CB',
 'NEDF',
 'DBP',
 'p68',
 'ABP1',
 'BTR',
 'CCK',
 'MIEF1',
 'RPL7P',
 'p150',
 'APC7',
 'RNASE9',
 'TTD',
 'ROC2',
 'FLJ10052',
 'ADRA1',
 'P13',
 'PLGLA1',
 'HBP',
 'ELP1',
 'BOLA2B',
 'CCN1',
 'BETA2',
 'HSJ2',
 'LYP',
 'MCT4',
 'SCYA2',
 'UBP',
 'MIRH1',
 'TPP1',
 'APG1',
 'FACE',
 'KNTC2AP',
 'NMI',
 'WDR82',
 'UCN2',
 'TCRGC2',
 'NAT3',
 'H2BFH',
 'TPSB2',
 'hg674',
 'OI12',
 'BEX1',
 'HC8',
 'BEC1',
 'NOP9',
 'H2BFG',
 'ST2',
 'CERS1',
 'EA1',
 'SAPL',
 'COD1',
 'HCRN',
 'VMA10',
 'FADS',
 'MRF1',
 'TCRAV30S1',
 'OR7E73P',
 'RPL29P3',
 'MIFR',
 'CAS1',
 'SPAG11A',
 'POP1',
 'ALDH4',
 'TNT',
 'CTB',
 'SNT1',
 'LMN2',
 'FAST',
 'PCDH11Y',
 'C6orf147',
 'H4C14',
 'BDPLT2',
 'OX2R',
 'MDC',
 'CRP3',
 'p60',
 'RGR',
 'POTE-15',
 'H5',
 'IBGC1, IBGC2',
 'DYT17',
 'p120',
 'MTTK',
 'oda6',
 'HL-2',
 'HL',
 'CLA1',
 'MRP',
 'HLA-DR1B',
 'HYPP',
 'BCAP',
 'TIP',
 'MIG7',
 'KAP4.7',
 'SCYL1',
 'SGT2',
 'SCZD9',
 'CHP',
 'NPL3',
 'ILT5',
 'CD14',
 'MRPL15',
 'TCS3',
 'ACA59',
 'SRC1',
 'C5A',
 'IGVH',
 'CTLA1',
 'OR1D4',
 'GK2',
 'L32mt',
 'LAN',
 'ST3GalA.2',
 'PAMP',
 'PUM',
 'COX1, COX3',
 'SIP-1',
 'CARMEN',
 'TRY-GTA5-5',
 'FA',
 'H2A.Bbd',
 'UBH1',
 'RBMY2',
 'UBCH8',
 'XLOC_000303',
 'ADAMTS-2',
 'GPT',
 'ST3',
 'ATX',
 'HCCR-1',
 'H4C16',
 'GLUT6',
 'HSP72',
 'DNAJ',
 'LIP1',
 'FCCMS',
 'PEPP2',
 'FY',
 'ESG1',
 'HHL',
 'TRD-GTC2-10',
 'ODS1',
 'MT-A70',
 'TC-1',
 'SUP',
 'EMILIN3',
 'MPI',
 'H2AC15',
 'ICLN',
 'CED-12',
 'SARA',
 'PPCD',
 'FRA',
 'PRP4',
 'EPPK',
 'HSTF1',
 'AP3AASE',
 'ARIP1',
 'LHFPL4',
 'p13',
 'USE1',
 'C16DUPp11.2',
 'IHG1',
 'PUMAG',
 'TRI-AAT5-2',
 'AG2',
 'ATD',
 'TAL-H',
 'TMSNB',
 'NOS2',
 'RBMY1C',
 'OR7-21',
 'BMS1P14',
 'DP',
 'P0',
 'TP1',
 'ALL1, GAS7, HRX',
 'BRX',
 'FADS3',
 'HSPCAL1',
 'UPA',
 'ADPRTL3',
 'SEPT2',
 'DYT23',
 'HGPS',
 'OTSC12',
 'OSX',
 'CCL15',
 'PXMP1',
 'C11orf48',
 'RBM14',
 'p48',
 'ELK2',
 'CP27',
 'BDPLT1',
 'BCR',
 'LAGE2B',
 'AAA1',
 'L9',
 'SCN1',
 'SPH2',
 'ARP4',
 'NUS1',
 'S100',
 'EIF3CL',
 'B29',
 'TRNAL-CAA',
 'C10orf50',
 'MRPS12',
 'XAP4',
 'HOX3',
 'APPL',
 'ICIS',
 'p20',
 'NIP1',
 'Stv1',
 'IBP1',
 'H2BC6',
 'CSBS',
 'HCA3',
 'HC3',
 'ASL',
 'MELF2',
 'SNRNP65',
 'Protease',
 'UTR',
 'HMGB1L1',
 'PEO',
 'ADF',
 'FADS2',
 'FX',
 'LNP1',
 'AIP1',
 'RP7',
 'PXR1',
 'MAP1A',
 'FAD1',
 'KAP10.9',
 'PRL1',
 'RIG',
 'TCRAV28S1',
 'PS2',
 'CT78',
 'SPDYE4',
 'NSCL2',
 'PHLP3',
 'ME2',
 'HNRNPCL2, HNRNPCL4',
 'DAO',
 'GH',
 'RBM2',
 'ZWS',
 'HPF1',
 'CDF',
 'FZD3',
 'MRP-S28',
 'HOX1',
 'NET7',
 'Oct-3',
 'CAL',
 'CEH',
 'RAE1',
 'UBC4',
 'C18ORF2',
 'KRTAP10-9',
 'PGII',
 'P180',
 'DIP',
 'TRY3',
 'CS-1',
 'CLIP',
 'ET',
 'APOC4',
 'C17orf106',
 'EEF-1',
 'ZNF182',
 'KRTAP2-3',
 'H2BC4',
 'FEB2',
 'RPL24',
 'P21',
 'TRIM34, TRIM6',
 'MZF-1',
 'MCT7',
 'GOT1B',
 'RER',
 'TAX1BP2',
 'PRG3',
 'C2orf47',
 'PACAP',
 'bHLHe42',
 'EIF-5A',
 'PB',
 'GUSBP1',
 'TRAD',
 'ACSM2',
 'ODC',
 'FCRL1',
 'BAL',
 'DESI2',
 'CGA',
 'MIO',
 'p60TRP',
 'PISD',
 'TRC-GCA2-3',
 'TSH1',
 'BDPLT14, THAS',
 'BNC1',
 'TCRBV21S1',
 'PORMIN',
 'CHIP28',
 'LMO4',
 'DLG1',
 'GLP-1',
 'AML1-EVI-1',
 'PLSCR3',
 'P28',
 'TEN1',
 'DDT',
 'HOX4',
 'SFTP1',
 'EJM4',
 'CAF-1',
 'EF1B',
 'NCL',
 'RCN3',
 'M130',
 'MCD',
 'DEFB4',
 'TTP',
 'KIAA0700',
 'BD-3',
 'EMT',
 '3-alpha-HSD',
 'SIT1',
 'G2',
 'CSN1',
 'D10S102',
 'OR11-55',
 'ESP1',
 'H2B/g',
 'BOR',
 'TOMM6',
 'IDH',
 'HBB',
 'MMDS3',
 'FEZ1',
 'CMT1',
 'ELOA3B',
 'CT45A3, CT45A6, CT45A7',
 'SLAP',
 'OR6-1',
 'PLD1',
 'L15',
 'OI4',
 'POLK',
 'UOG1',
 'SBP',
 'NAC1',
 'MEL',
 'PKB',
 'PRX',
 'BWS',
 'PORC',
 'ARF1',
 'ZNF2',
 'RPL7AP3',
 'BP75',
 'MPS1',
 'TRIM49B',
 'GCP2',
 'INPP5E',
 'MIZ',
 'HMSNP',
 'EF1A',
 'FAM25A, FAM25C, FAM25G',
 'PSP',
 'TIRP',
 'LGALS7',
 'OR912-110',
 'VSD1',
 'NK1',
 'HH1',
 'RIP1',
 'SMRP',
 'C1',
 'C11orf2',
 'KLIP1',
 'B9',
 'SOHLH2',
 'HHM',
 'H2AC17',
 'PHKD',
 'DDAH',
 'RGL1',
 'RNU12',
 'AHA1',
 'RCA1',
 'IGH',
 'CA11',
 'RBP',
 'LIPB',
 'FHOD3',
 'SPC7',
 'LINC00092',
 'Tmp-21-I',
 'HRS',
 'BCL5',
 'CCP1',
 'CTF',
 'FACD',
 'UGT1A1',
 'FIR',
 'EHK2',
 'CPT1',
 'PGD',
 'V1S5P',
 'FA1',
 'ST2L',
 'KRAS',
 'P51',
 'BOCA',
 'STP',
 'TCI',
 'RDC-1',
 'H2AC11, H2AC13, H2AC14, H2AC16, H2AC17',
 'STAG3L2, STAG3L3',
 'TC1',
 'PAFAH',
 'MGA',
 'ARPIN',
 'TRBP',
 'GRIK2',
 'PDA2',
 'LGMD1E',
 'RNF51',
 'B5',
 'NS',
 'CDH20',
 'AE2',
 'TCRAV12S1',
 'NIP',
 'hg523',
 'FCG3',
 'MRX2',
 'BG',
 'CPAD',
 'LINC00846',
 'RNF3',
 'MCPH4',
 'LINC00087',
 'CAM2',
 'PTG',
 'ROX',
 'RED',
 'DUX1',
 'TRNAQ49P',
 'NOD5',
 'H4C1, H4C11, H4C12, H4C14, H4C15, H4C16, H4C2, H4C3, H4C4, H4C5, H4C6, H4C8, H4C9',
 'TCEB3L2',
 'ESG',
 'IGLC6',
 'IGHD1B',
 'TRF',
 'LYS2',
 'GEMIN1',
 'PRGA',
 'CRN',
 'RFMN',
 'C3PO',
 'H2BC10, H2BC4, H2BC6, H2BC8',
 'CBP',
 'ZNF581',
 'DESI1',
 'hBD-4',
 'LBP',
 'NUBP1',
 'TRF-GAA1-5',
 'GP',
 'UGT1C',
 'GAGE-2',
 'H4C9',
 'GLUT8',
 'SMIM10L3',
 'PKK',
 'D3',
 'SIN',
 'G15',
 'CD1A',
 'CypD',
 'P2RY11, PPAN',
 'TRIP',
 'CTPA',
 'AGT1',
 'FAM18B2',
 'UPP',
 'PPT',
 'ARPC4',
 'NCRNA00087',
 'G0S19-2',
 'PACER',
 'IDDM1',
 'ZSCAN30',
 'SIR2',
 'KIR2DL3',
 'PFHB1',
 'GLYT2',
 'RAET1H',
 'MYZAP',
 'THY1-AS1',
 'PD1',
 'ALG2',
 'B1',
 'MTCO2',
 'TTLL5',
 'CAK1',
 'CACC',
 'REF1',
 'SWD2',
 'WSS',
 'BS',
 'MME',
 'BRPF1',
 'LDB1',
 'CEA',
 'UFD2',
 'PARF',
 'MUC3',
 'TRB1',
 'MRPS35',
 'CYP2A',
 'CCD1',
 'HOX2',
 'RPL10',
 'CPBHM',
 'ILWEQ',
 'SIGLECL1',
 'P29',
 'ZP1',
 'MCDR1',
 'GC',
 'BAF190',
 'RAB39',
 'CDP',
 'TRD',
 'PFD',
 'GPXL2',
 'CT4.8',
 'FEZ',
 'AOMS4',
 'EHK',
 'TCF6L1',
 'FBXW6',
 'OBTP',
 'SPANX',
 'SPATA31C2',
 'ACAT2',
 'PH2',
 'TSBP',
 'CBBM',
 'H2BC10',
 'INT4',
 'CKR-1',
 'CTSO1',
 'NSL1',
 'AGS3',
 'DLG3',
 'PIGU',
 'SEN1',
 'CXorf52',
 'FAME',
 'DSC1, DSC2',
 'TTTY6',
 'HAS',
 'MIG12',
 'TUBB',
 'KFSDX',
 'HNRPA3',
 'LAMA3',
 'MINT',
 'MLL2',
 'TYRO4',
 'RRP17',
 'GBBB2',
 'PE-1',
 'POTE22',
 'CV2',
 'ERG-1',
 'S11',
 'INCA',
 'GRP',
 'ARF1P2',
 'PBCRA',
 'NRK2',
 'USP21',
 'CLPSMCR',
 'CFTD',
 'T2D',
 'HIST1H2BE',
 'RNASEH1, RNH1',
 'ASC1',
 'TAF2A',
 'ZNF102',
 'OCT3',
 'H3C13',
 'TRR-TCT3-2',
 'BCS1',
 'CLP1',
 'GAGE-8',
 'TRQ-CTG1-3',
 'ECEL1P1',
 'TBC1D3, TBC1D3H',
 'H2AC4',
 'NLF1',
 'BIS',
 'WDR11',
 'NAT-1',
 'CAMIII',
 'SGN1',
 'CT45A6',
 'AIBP',
 'L30',
 'CHD5',
 'STV1',
 'RAB7',
 'RBP1',
 'P65',
 'TCRAV7S1',
 'OR52I1',
 'TRI-AAT5-3',
 'PCA1',
 'CCNL1',
 'H3C14, H3C15',
 'TCRBV25S1',
 'COT',
 'AD9',
 'IL25, IL27',
 'CBG',
 'EXT2',
 'CCL',
 'APOBEC3A',
 'ARC20',
 'RPEL1',
 'USP10',
 'MCM',
 'EAF1',
 'HIST1H2BG',
 'ARC',
 'TCEA1',
 'TTTY8',
 'PTC1',
 'CDH19',
 'CRA',
 'COX',
 'B4',
 'ACTP1',
 'TTTY23B',
 'TBC1D3C, TBC1D3D',
 'TMSB15B',
 'PLAP',
 'ciRS-7',
 'TDGF2',
 'MRX92',
 'RNASEH1',
 'MMD1',
 'IL-27',
 'CART1',
 'RP3',
 'FOXD4L2',
 'psiSSX8',
 'IP3R',
 'DEFB-8',
 'SULT1A3',
 'OR19-7',
 'CLIP4',
 'LEPR',
 'P84',
 'PSP2',
 'F5F8D',
 'PBF',
 '60B8AG',
 'TSSK4',
 'IGNT',
 'DOK1',
 'SMO',
 'TCRAV8S1',
 'ICBP90',
 'TGM6',
 'EAP1',
 'RAR',
 'CSS1',
 'ECD',
 'ERIS',
 'SAX3',
 'RAB1C',
 'MRXS32',
 'ADRA1A',
 'DOR',
 'OR7E74P',
 'RNF89',
 'ALG10',
 'GAAP',
 'TMED10',
 'ATP1A1',
 'XAGE1B',
 'UGT',
 'NOP',
 'dJ222E13.1',
 'CREB-2',
 'LPP1',
 'MIC1',
 'OR11-13',
 'KIAA0229',
 'LIM1',
 'HDLCQ7',
 'COD2',
 'RAC3',
 'IMP1',
 'TRMT1',
 'MED25',
 'NAT1, NET1, SLC6A5',
 'ACTL6',
 'LCN5',
 'POTED',
 'GGT',
 'ORC2',
 'DCR',
 'OS4, SCP2',
 'MRP-L15',
 'CHD2',
 'PFM1',
 'NRF2',
 'ZNT8',
 'A26B3',
 'RNA18S5',
 'DS',
 'RPS17L2',
 'ENO1-IT1',
 'p110',
 'GRO1',
 'CD98',
 'CMC1',
 'IRBP',
 'ARG',
 'P8MTCP1',
 'H2',
 'LAT1',
 'U19',
 'PMS2L11',
 'ZC3H18',
 'ARP3',
 'ALIEN',
 'CLAMP',
 'TRR-ACG1-3',
 'BRF2',
 'PSS3',
 'MROH7',
 'C9orf36',
 'IGHV4-3',
 'TMS-1',
 'LGCR',
 'PKD2',
 'PABP2',
 'SNF2',
 'ALS19',
 'SIMP',
 'CLK-1',
 'MRPL28',
 'MARS',
 'DVL',
 'UbcM2',
 'SMAC3L',
 'RN',
 'P85',
 'PPD',
 'PC1',
 'PRO1068',
 'ELOA3',
 'DVL1L1',
 'TSH2',
 'MRPL27',
 'TRX2',
 'HIP',
 'DP1',
 'ST1A4',
 'ACTBL1',
 'ETL1',
 'BCH',
 ...}

In [ ]:
# with open('ambiguous_symbol_set.txt', 'w') as file:
#     for item in ambiguous_symbol_set:
#         file.write(f"{item.strip()}\n")

In [ ]:
# with open('ambiguous_symbol_set.txt', 'r') as file:
#     # Read each line, strip newline characters, and convert to a set
#     ambiguous_symbol_set = set(line.strip() for line in file)
# len(ambiguous_symbol_set)

## <a id='toc7_'></a>[May or may not be nonesense](#toc0_)

In [ ]:
name_ensg_notmatch = dgidb_name_set.difference(ensg_gene_symbol_set)
len(name_ensg_notmatch)

298

In [ ]:
gene_claim_name_ensg_notmatch = dgidb_gene_claim_name_set.difference(
    ensg_gene_symbol_set
)
len(gene_claim_name_ensg_notmatch)

15029

In [ ]:
cleaned_gene_claim_name_ensg_notmatch = [
    x for x in gene_claim_name_ensg_notmatch if str(x) != "NaN"
]
len(cleaned_gene_claim_name_ensg_notmatch)

15029

In [ ]:
name_hgnc_notmatch = dgidb_name_set.difference(hgnc_gene_symbol_set)
len(name_hgnc_notmatch)

25

In [ ]:
name_hngc_notmatch_aacollision = name_hgnc_notmatch.intersection(
    hgnc_alias_alias_collision_set
)
len(name_hngc_notmatch_aacollision)

0

In [ ]:
cleaned_name_hgnc_notmatch = [x for x in name_hgnc_notmatch if str(x) != "NaN"]
len(cleaned_name_hgnc_notmatch)

25

In [ ]:
gene_claim_name_hgnc_notmatch = dgidb_gene_claim_name_set.difference(
    hgnc_gene_symbol_set
)
len(gene_claim_name_hgnc_notmatch)

14755

In [ ]:
name_ncbi_notmatch = dgidb_name_set.difference(ncbi_gene_symbol_set)
len(name_ncbi_notmatch)

97

In [ ]:
name_ncbi_notmatch_aacollision = name_ncbi_notmatch.intersection(
    ncbi_alias_alias_collision_set
)
len(name_ncbi_notmatch_aacollision)

2

In [ ]:
name_ncbi_hgnc_notmatch = name_ncbi_notmatch.difference(hgnc_gene_symbol_set)
len(name_ncbi_hgnc_notmatch)

9

In [ ]:
name_ncbi_hgnc_ensg_notmatch = name_ncbi_hgnc_notmatch.difference(ensg_gene_symbol_set)
len(name_ncbi_hgnc_ensg_notmatch)

8

In [ ]:
gene_claim_name_ncbi_notmatch = dgidb_gene_claim_name_set.difference(
    ncbi_gene_symbol_set
)
len(gene_claim_name_ncbi_notmatch)

14828

In [ ]:
gene_claim_name_ncbi_hngc_notmatch = gene_claim_name_ncbi_notmatch.difference(
    hgnc_gene_symbol_set
)
len(gene_claim_name_ncbi_hngc_notmatch)

14738

In [ ]:
gene_claim_name_ncbi_hngc_ensg_notmatch = gene_claim_name_ncbi_hngc_notmatch.difference(
    ensg_gene_symbol_set
)
len(gene_claim_name_ncbi_hngc_ensg_notmatch)

14735

In [ ]:
name_hgnc_match = dgidb_name_set.intersection(hgnc_gene_symbol_set)
len(name_hgnc_match)

11976

In [ ]:
name_hgnc_match_aacollision = name_hgnc_match.intersection(
    hgnc_alias_alias_collision_set
)
len(name_hgnc_match_aacollision)

8

In [ ]:
name_ensg_match = dgidb_name_set.intersection(ensg_gene_symbol_set)
len(name_ensg_match)

11703

In [ ]:
name_ncbi_match = dgidb_name_set.intersection(ncbi_gene_symbol_set)
len(name_ncbi_match)

11904

In [ ]:
name_ncbi_match_aacollision = name_ncbi_match.intersection(
    ncbi_alias_alias_collision_set
)
len(name_ncbi_match_aacollision)

124

In [ ]:
name_ncbi_ensg_match = name_ncbi_match.intersection(ensg_gene_symbol_set)
len(name_ncbi_ensg_match)

11685

In [ ]:
name_ncbi_ensg_hgnc_match = name_ncbi_ensg_match.intersection(hgnc_gene_symbol_set)
len(name_ncbi_ensg_hgnc_match)

11684

In [ ]:
gene_claim_name_hgnc_match = dgidb_gene_claim_name_set.intersection(
    hgnc_gene_symbol_set
)
len(gene_claim_name_hgnc_match)

11984

In [ ]:
gene_claim_name_ensg_match = dgidb_gene_claim_name_set.intersection(
    ensg_gene_symbol_set
)
len(gene_claim_name_ensg_match)

11710

In [ ]:
gene_claim_name_ensg_aacollision_match = dgidb_gene_claim_name_set.intersection(
    ensg_alias_alias_collision_set
)
len(gene_claim_name_ensg_aacollision_match)

23

In [ ]:
gene_claim_name_hgnc_aacollision_match = dgidb_gene_claim_name_set.intersection(
    hgnc_alias_alias_collision_set
)
len(gene_claim_name_hgnc_aacollision_match)

21

In [ ]:
gene_claim_name_ncbi_aacollision_match = dgidb_gene_claim_name_set.intersection(
    ncbi_alias_alias_collision_set
)
len(gene_claim_name_ncbi_aacollision_match)

221

In [ ]:
name_ensg_aacollision_match = dgidb_name_set.intersection(
    ensg_alias_alias_collision_set
)
len(name_ensg_aacollision_match)

9

In [ ]:
name_hgnc_aacollision_match = dgidb_name_set.intersection(
    hgnc_alias_alias_collision_set
)
len(name_hgnc_aacollision_match)

8

In [ ]:
name_ncbi_aacollision_match = dgidb_name_set.intersection(
    ncbi_alias_alias_collision_set
)
len(name_ncbi_aacollision_match)

126

In [ ]:
gene_claim_name_hgnc_notmatch = dgidb_gene_claim_name_set.difference(
    hgnc_gene_symbol_set
)
len(gene_claim_name_hgnc_notmatch)

14755

In [ ]:
gene_claim_name_hgnc_notmatch_aacollision = gene_claim_name_hgnc_notmatch.intersection(
    hgnc_alias_alias_collision_set
)
len(gene_claim_name_hgnc_notmatch_aacollision)

13

In [ ]:
gene_claim_name_ensg_notmatch = dgidb_gene_claim_name_set.difference(
    ensg_gene_symbol_set
)
len(gene_claim_name_ensg_notmatch)

15029

In [ ]:
gene_claim_name_ncbi_notmatch = dgidb_gene_claim_name_set.difference(
    ncbi_gene_symbol_set
)
len(gene_claim_name_ncbi_notmatch)

14828

In [ ]:
gene_claim_name_ncbi_notmatch_aacollision = gene_claim_name_ncbi_notmatch.intersection(
    ncbi_alias_alias_collision_set
)
len(gene_claim_name_ncbi_notmatch_aacollision)

97

In [ ]:
gene_claim_name_hgnc_match = dgidb_gene_claim_name_set.intersection(
    hgnc_gene_symbol_set
)
len(gene_claim_name_hgnc_match)

11984

In [ ]:
gene_claim_name_hgnc_match_aacollision = gene_claim_name_hgnc_match.intersection(
    hgnc_alias_alias_collision_set
)
len(gene_claim_name_hgnc_match_aacollision)

8

In [ ]:
gene_claim_name_ncbi_match = dgidb_gene_claim_name_set.intersection(
    ncbi_gene_symbol_set
)
len(gene_claim_name_ncbi_match)

11911

In [ ]:
gene_claim_name_ncbi_match_aacollision = gene_claim_name_ncbi_match.intersection(
    ncbi_alias_alias_collision_set
)
len(gene_claim_name_ncbi_match_aacollision)

124

In [ ]:
name_ensg_match_aacollision = name_ensg_match.intersection(
    ensg_alias_alias_collision_set
)
len(name_ensg_match_aacollision)

8

In [ ]:
len(gene_claim_name_ncbi_hngc_ensg_notmatch)

14735

In [ ]:
len(name_ncbi_hgnc_ensg_notmatch)

8

In [ ]:
len(dgidb_name_set)

12001

In [ ]:
len(dgidb_gene_claim_name_set)

26739

In [ ]:
name_ensg_notmatch_aacollision = name_ensg_notmatch.intersection(
    ensg_alias_alias_collision_set
)
len(name_ensg_notmatch_aacollision)

1

In [ ]:
gene_claim_name_ensg_match_aacollision = gene_claim_name_ensg_match.intersection(
    ensg_alias_alias_collision_set
)
len(gene_claim_name_ensg_match_aacollision)

8

In [ ]:
gene_claim_name_ensg_notmatch_aacollision = gene_claim_name_ensg_notmatch.intersection(
    ensg_alias_alias_collision_set
)
len(gene_claim_name_ensg_notmatch_aacollision)

15

In [ ]:
gene_claim_name_ncbi_notmatch_aacollision = gene_claim_name_ncbi_notmatch.intersection(
    ncbi_alias_alias_collision_set
)
len(gene_claim_name_ncbi_notmatch_aacollision)

97

In [ ]:
gene_claim_name_ncbi_match_aacollision = gene_claim_name_ncbi_match.intersection(
    ncbi_alias_alias_collision_set
)
len(gene_claim_name_ncbi_match_aacollision)

124

In [ ]:
gene_claim_name_hgnc_match_aacollision = gene_claim_name_hgnc_match.intersection(
    hgnc_alias_alias_collision_set
)
len(gene_claim_name_hgnc_match_aacollision)

8

In [ ]:
gene_claim_name_hgnc_notmatch_aacollision = gene_claim_name_hgnc_notmatch.intersection(
    hgnc_alias_alias_collision_set
)
len(gene_claim_name_hgnc_notmatch_aacollision)

13

## <a id='toc8_'></a>[Pull out instances of claim symbols that match to a primary gene symbol and the corresponding group symbols not matching to a primary gene symbol. Check for patterns of modes of error](#toc0_)

In [ ]:
dgidb_gene_df["claim_ambiguous_status"] = dgidb_gene_df["gene_claim_name"].isin(
    ambiguous_symbol_set
)
dgidb_gene_df

,gene_claim_name,nomenclature,concept_id,gene_name,source_db_name,source_db_version,claim_ambiguous_status
0,NGFIBA,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False
1,NGFIBB,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False
2,DAX,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False
3,REV-ERBA,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False
4,COUP2,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False
...,...,...,...,...,...,...,...
80229,KIT,Gene Symbol,hgnc:6342,KIT,Oncomine,v3,False
80230,HES1,Gene Name,hgnc:5192,HES1,NCI,14-Sep-17,True
80231,IRF1,Gene Symbol,hgnc:6116,IRF1,Tempus,11-Nov-18,False
80232,SHFM1,Gene Name,hgnc:10845,SEM1,DTC,9/2/20,True
80233,NEUROD1,Gene Name,hgnc:7762,NEUROD1,NCI,14-Sep-17,False

In [ ]:
dgidb_gene_df["claim_ambiguous_status"].value_counts()

claim_ambiguous_status
False    75819
True      4415
Name: count, dtype: int64

In [ ]:
ambiguous_claim_df = dgidb_gene_df.loc[dgidb_gene_df["claim_ambiguous_status"]]
ambiguous_claim_df

,gene_claim_name,nomenclature,concept_id,gene_name,source_db_name,source_db_version,claim_ambiguous_status
18,TR2,NCBI Gene Name,hgnc:7971,NR2C1,BaderLab,Feb-14,True
23,SF1,NCBI Gene Name,hgnc:12950,SF1,BaderLab,Feb-14,True
24,HNF4A,NCBI Gene Name,hgnc:5024,HNF4A,BaderLab,Feb-14,True
34,GR,NCBI Gene Name,hgnc:7978,NR3C1,BaderLab,Feb-14,True
35,PR,NCBI Gene Name,hgnc:18216,TMEM37,BaderLab,Feb-14,True
...,...,...,...,...,...,...,...
80214,PMP22,Gene Name,hgnc:9118,PMP22,DTC,9/2/20,True
80225,GPI,Gene Name,hgnc:4458,GPI,NCI,14-Sep-17,True
80227,BCR,Gene Name,hgnc:1014,BCR,FDA,10-Apr-24,True
80230,HES1,Gene Name,hgnc:5192,HES1,NCI,14-Sep-17,True
80232,SHFM1,Gene Name,hgnc:10845,SEM1,DTC,9/2/20,True

In [ ]:
ambiguous_claim_df.loc[ambiguous_claim_df["gene_claim_name"] == "TR2"]

,gene_claim_name,nomenclature,concept_id,gene_name,source_db_name,source_db_version,claim_ambiguous_status
18,TR2,NCBI Gene Name,hgnc:7971,NR2C1,BaderLab,Feb-14,True

In [ ]:
dgidb_gene_df["name_ambiguous_status"] = dgidb_gene_df["gene_name"].isin(
    ambiguous_symbol_set
)
dgidb_gene_df

,gene_claim_name,nomenclature,concept_id,gene_name,source_db_name,source_db_version,claim_ambiguous_status,name_ambiguous_status
0,NGFIBA,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False
1,NGFIBB,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False
2,DAX,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False
3,REV-ERBA,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False
4,COUP2,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False
...,...,...,...,...,...,...,...,...
80229,KIT,Gene Symbol,hgnc:6342,KIT,Oncomine,v3,False,False
80230,HES1,Gene Name,hgnc:5192,HES1,NCI,14-Sep-17,True,True
80231,IRF1,Gene Symbol,hgnc:6116,IRF1,Tempus,11-Nov-18,False,False
80232,SHFM1,Gene Name,hgnc:10845,SEM1,DTC,9/2/20,True,False
80233,NEUROD1,Gene Name,hgnc:7762,NEUROD1,NCI,14-Sep-17,False,False

In [ ]:
dgidb_gene_df["name_ambiguous_status"].value_counts()

name_ambiguous_status
False    75009
True      5225
Name: count, dtype: int64

In [ ]:
dgidb_gene_df["claim_primary_status"] = dgidb_gene_df["gene_claim_name"].isin(
    hgnc_ensg_ncbi_gene_symbol_set
)
dgidb_gene_df

,gene_claim_name,nomenclature,concept_id,gene_name,source_db_name,source_db_version,claim_ambiguous_status,name_ambiguous_status,claim_primary_status
0,NGFIBA,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False
1,NGFIBB,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False
2,DAX,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False
3,REV-ERBA,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False
4,COUP2,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False
...,...,...,...,...,...,...,...,...,...
80229,KIT,Gene Symbol,hgnc:6342,KIT,Oncomine,v3,False,False,True
80230,HES1,Gene Name,hgnc:5192,HES1,NCI,14-Sep-17,True,True,True
80231,IRF1,Gene Symbol,hgnc:6116,IRF1,Tempus,11-Nov-18,False,False,True
80232,SHFM1,Gene Name,hgnc:10845,SEM1,DTC,9/2/20,True,False,False
80233,NEUROD1,Gene Name,hgnc:7762,NEUROD1,NCI,14-Sep-17,False,False,True

In [ ]:
dgidb_gene_df["claim_primary_status"].value_counts()

claim_primary_status
True     64209
False    16025
Name: count, dtype: int64

In [ ]:
dgidb_gene_df["name_primary_status"] = (
    dgidb_gene_df["gene_name"].astype(str).isin(hgnc_ensg_ncbi_gene_symbol_set)
)
dgidb_gene_df

,gene_claim_name,nomenclature,concept_id,gene_name,source_db_name,source_db_version,claim_ambiguous_status,name_ambiguous_status,claim_primary_status,name_primary_status
0,NGFIBA,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False
1,NGFIBB,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False
2,DAX,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False
3,REV-ERBA,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False
4,COUP2,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
80229,KIT,Gene Symbol,hgnc:6342,KIT,Oncomine,v3,False,False,True,True
80230,HES1,Gene Name,hgnc:5192,HES1,NCI,14-Sep-17,True,True,True,True
80231,IRF1,Gene Symbol,hgnc:6116,IRF1,Tempus,11-Nov-18,False,False,True,True
80232,SHFM1,Gene Name,hgnc:10845,SEM1,DTC,9/2/20,True,False,False,True
80233,NEUROD1,Gene Name,hgnc:7762,NEUROD1,NCI,14-Sep-17,False,False,True,True

In [ ]:
dgidb_gene_df["name_primary_status"].value_counts()

name_primary_status
True     78074
False     2160
Name: count, dtype: int64

In [ ]:
not_primary_group_name_df = dgidb_gene_df.loc[~dgidb_gene_df["name_primary_status"]]
not_primary_group_name_df

,gene_claim_name,nomenclature,concept_id,gene_name,source_db_name,source_db_version,claim_ambiguous_status,name_ambiguous_status,claim_primary_status,name_primary_status
0,NGFIBA,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False
1,NGFIBB,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False
2,DAX,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False
3,REV-ERBA,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False
4,COUP2,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
57108,NCBIGENE:2614,NCBI Gene ID,ncbigene:2614,GAPDHL17,GuideToPharmacology,2024.1,False,False,False,False
57552,CYB5P1,Gene Symbol,ncbigene:1529,CYB5P1,NCBI,20240410,False,False,False,False
66195,OA1,Gene Symbol,ncbigene:474285,OA1,NCBI,20240410,False,False,False,False
66196,OA1,Gene Symbol,ncbigene:474285,OA1,dGene,27-Jun-13,False,False,False,False
74562,ATP5A2,Gene Symbol,ncbigene:499,ATP5A2,NCBI,20240410,False,False,False,False

In [ ]:
not_primary_group_name_df["name_alias_status"] = dgidb_gene_df["gene_name"].isin(
    hgnc_ensg_ncbi_alias_symbol_set
)
not_primary_group_name_df

/var/folders/vt/znzp_c6s02q6kjcmqfk0cb500000gq/T/ipykernel_37476/2466900690.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  not_primary_group_name_df['name_alias_status'] = dgidb_gene_df['gene_name'].isin(hgnc_ensg_ncbi_alias_symbol_set)

,gene_claim_name,nomenclature,concept_id,gene_name,source_db_name,source_db_version,claim_ambiguous_status,name_ambiguous_status,claim_primary_status,name_primary_status,name_alias_status
0,NGFIBA,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False,False
1,NGFIBB,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False,False
2,DAX,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False,False
3,REV-ERBA,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False,False
4,COUP2,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
57108,NCBIGENE:2614,NCBI Gene ID,ncbigene:2614,GAPDHL17,GuideToPharmacology,2024.1,False,False,False,False,False
57552,CYB5P1,Gene Symbol,ncbigene:1529,CYB5P1,NCBI,20240410,False,False,False,False,False
66195,OA1,Gene Symbol,ncbigene:474285,OA1,NCBI,20240410,False,False,False,False,True
66196,OA1,Gene Symbol,ncbigene:474285,OA1,dGene,27-Jun-13,False,False,False,False,True
74562,ATP5A2,Gene Symbol,ncbigene:499,ATP5A2,NCBI,20240410,False,False,False,False,False

In [ ]:
not_primary_group_name_df["name_alias_status"].value_counts()

name_alias_status
False    2154
True        6
Name: count, dtype: int64

In [ ]:
print("Calmbp1" in hgnc_ensg_ncbi_alias_symbol_set)

True

In [ ]:
not_primary_group_name_df["claim_alias_status"] = dgidb_gene_df["gene_claim_name"].isin(
    hgnc_ensg_ncbi_alias_symbol_set
)
not_primary_group_name_df

/var/folders/vt/znzp_c6s02q6kjcmqfk0cb500000gq/T/ipykernel_37476/1565248528.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  not_primary_group_name_df['claim_alias_status'] = dgidb_gene_df['gene_claim_name'].isin(hgnc_ensg_ncbi_alias_symbol_set)

,gene_claim_name,nomenclature,concept_id,gene_name,source_db_name,source_db_version,claim_ambiguous_status,name_ambiguous_status,claim_primary_status,name_primary_status,name_alias_status,claim_alias_status
0,NGFIBA,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False,False,False
1,NGFIBB,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False,False,False
2,DAX,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False,False,False
3,REV-ERBA,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False,False,False
4,COUP2,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
57108,NCBIGENE:2614,NCBI Gene ID,ncbigene:2614,GAPDHL17,GuideToPharmacology,2024.1,False,False,False,False,False,False
57552,CYB5P1,Gene Symbol,ncbigene:1529,CYB5P1,NCBI,20240410,False,False,False,False,False,False
66195,OA1,Gene Symbol,ncbigene:474285,OA1,NCBI,20240410,False,False,False,False,True,True
66196,OA1,Gene Symbol,ncbigene:474285,OA1,dGene,27-Jun-13,False,False,False,False,True,True
74562,ATP5A2,Gene Symbol,ncbigene:499,ATP5A2,NCBI,20240410,False,False,False,False,False,False

In [ ]:
alias_not_primary_group_name_df = not_primary_group_name_df.loc[
    not_primary_group_name_df["name_alias_status"]
]
alias_not_primary_group_name_df

,gene_claim_name,nomenclature,concept_id,gene_name,source_db_name,source_db_version,claim_ambiguous_status,name_ambiguous_status,claim_primary_status,name_primary_status,name_alias_status,claim_alias_status
3251,USP17L,Gene Symbol,ncbigene:100862847,USP17L,dGene,27-Jun-13,False,False,False,False,True,True
23020,ACTIN,Gene Name,ncbigene:389036,ACT,TTD,2020.06.01,False,True,False,False,True,False
38737,USP17L,Gene Symbol,ncbigene:100862847,USP17L,NCBI,20240410,False,False,False,False,True,True
55006,ACT,Gene Symbol,ncbigene:389036,ACT,NCBI,20240410,True,True,False,False,True,True
66195,OA1,Gene Symbol,ncbigene:474285,OA1,NCBI,20240410,False,False,False,False,True,True
66196,OA1,Gene Symbol,ncbigene:474285,OA1,dGene,27-Jun-13,False,False,False,False,True,True

In [ ]:
not_primary_group_name_df["name_null_status"] = dgidb_gene_df["gene_name"].isnull()
not_primary_group_name_df

/var/folders/vt/znzp_c6s02q6kjcmqfk0cb500000gq/T/ipykernel_37476/743224626.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  not_primary_group_name_df['name_null_status'] = dgidb_gene_df['gene_name'].isnull()

,gene_claim_name,nomenclature,concept_id,gene_name,source_db_name,source_db_version,claim_ambiguous_status,name_ambiguous_status,claim_primary_status,name_primary_status,name_alias_status,claim_alias_status,name_null_status
0,NGFIBA,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False,False,False,True
1,NGFIBB,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False,False,False,True
2,DAX,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False,False,False,True
3,REV-ERBA,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False,False,False,True
4,COUP2,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
57108,NCBIGENE:2614,NCBI Gene ID,ncbigene:2614,GAPDHL17,GuideToPharmacology,2024.1,False,False,False,False,False,False,False
57552,CYB5P1,Gene Symbol,ncbigene:1529,CYB5P1,NCBI,20240410,False,False,False,False,False,False,False
66195,OA1,Gene Symbol,ncbigene:474285,OA1,NCBI,20240410,False,False,False,False,True,True,False
66196,OA1,Gene Symbol,ncbigene:474285,OA1,dGene,27-Jun-13,False,False,False,False,True,True,False
74562,ATP5A2,Gene Symbol,ncbigene:499,ATP5A2,NCBI,20240410,False,False,False,False,False,False,False

In [ ]:
not_primary_group_name_df["name_null_status"].value_counts()

name_null_status
True     2144
False      16
Name: count, dtype: int64

In [ ]:
null_not_primary_group_name_df = not_primary_group_name_df.loc[
    not_primary_group_name_df["name_null_status"]
]
null_not_primary_group_name_df

,gene_claim_name,nomenclature,concept_id,gene_name,source_db_name,source_db_version,claim_ambiguous_status,name_ambiguous_status,claim_primary_status,name_primary_status,name_alias_status,claim_alias_status,name_null_status
0,NGFIBA,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False,False,False,True
1,NGFIBB,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False,False,False,True
2,DAX,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False,False,False,True
3,REV-ERBA,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False,False,False,True
4,COUP2,NCBI Gene Name,NaN,NaN,BaderLab,Feb-14,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
29008,URS00006E35E8_9606,Gene Symbol,NaN,NaN,GO,10-Apr-24,False,False,False,False,False,False,True
29009,URS0000EA3BA1_9606,Gene Symbol,NaN,NaN,GO,10-Apr-24,False,False,False,False,False,False,True
29198,TRYPTASE_B2_HUMAN,Gene Symbol,NaN,NaN,GO,10-Apr-24,False,False,False,False,False,False,True
29199,TRYPTASE_B1_HUMAN,Gene Symbol,NaN,NaN,GO,10-Apr-24,False,False,False,False,False,False,True
29389,HERVK_113,Gene Symbol,NaN,NaN,Pharos,10-Apr-24,False,False,False,False,False,False,True

In [ ]:
null_not_primary_group_name_df["gene_claim_name"].value_counts()

gene_claim_name
ATPF                 2
RPSK                 2
RPSE                 2
RPSD                 2
RPSC                 2
                    ..
YCEI                 1
CEFE                 1
NFSB                 1
LIGA                 1
TRYPTASE_B1_HUMAN    1
Name: count, Length: 2053, dtype: int64

In [ ]:
null_not_primary_group_name_df.loc[null_not_primary_group_name_df["claim_alias_status"]]

Empty DataFrame
Columns: [gene_claim_name, nomenclature, concept_id, gene_name, source_db_name, source_db_version, claim_ambiguous_status, name_ambiguous_status, claim_primary_status, name_primary_status, name_alias_status, claim_alias_status, name_null_status]
Index: []

In [ ]:
other_not_primary_group_name_df = not_primary_group_name_df.loc[
    ~not_primary_group_name_df["name_alias_status"]
    & ~not_primary_group_name_df["name_null_status"]
]
other_not_primary_group_name_df

,gene_claim_name,nomenclature,concept_id,gene_name,source_db_name,source_db_version,claim_ambiguous_status,name_ambiguous_status,claim_primary_status,name_primary_status,name_alias_status,claim_alias_status,name_null_status
22269,MELANOCORTIN RECEPTOR,Gene Name,ncbigene:359995,mCR,TTD,2020.06.01,False,False,False,False,False,False,False
25653,NCBIGENE:697,NCBI Gene ID,ncbigene:697,BTNL1,GuideToPharmacology,2024.1,False,False,False,False,False,False,False
26457,NCBIGENE:1529,NCBI Gene ID,ncbigene:1529,CYB5P1,GuideToPharmacology,2024.1,False,False,False,False,False,False,False
26608,NCBIGENE:499,NCBI Gene ID,ncbigene:499,ATP5A2,GuideToPharmacology,2024.1,False,False,False,False,False,False,False
54783,mCR,Gene Symbol,ncbigene:359995,mCR,NCBI,20240410,False,False,False,False,False,False,False
56710,BTNL1,Gene Symbol,ncbigene:697,BTNL1,NCBI,20240410,False,False,False,False,False,False,False
57107,GAPDHL17,Gene Symbol,ncbigene:2614,GAPDHL17,NCBI,20240410,False,False,False,False,False,False,False
57108,NCBIGENE:2614,NCBI Gene ID,ncbigene:2614,GAPDHL17,GuideToPharmacology,2024.1,False,False,False,False,False,False,False
57552,CYB5P1,Gene Symbol,ncbigene:1529,CYB5P1,NCBI,20240410,False,False,False,False,False,False,False
74562,ATP5A2,Gene Symbol,ncbigene:499,ATP5A2,NCBI,20240410,False,False,False,False,False,False,False

In [ ]:
claim_true_name_false_df = dgidb_gene_df.loc[
    dgidb_gene_df["claim_primary_status"] & ~dgidb_gene_df["name_primary_status"]
]
claim_true_name_false_df

Empty DataFrame
Columns: [gene_claim_name, nomenclature, concept_id, gene_name, source_db_name, source_db_version, claim_ambiguous_status, name_ambiguous_status, claim_primary_status, name_primary_status]
Index: []

In [ ]:
len(claim_true_name_false_df)

0